// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuotesController from "./quotes_controller"
application.register("quotes", QuotesController)

import TasksController from "./tasks_controller"
application.register("tasks", TasksController)

import TodosController from "./todos_controller"
application.register("todos", TodosController)
